### PR TITLE
Test - HRRR Nomads - Suggest change for CLI tests.

### PR DESCRIPTION
**Pull request by jomey**
Be more specific in assertion calls instead of a call count.

### CODE REVIEW

**Comment by scotthavens** [comment]
This changes the test from actually calling `HRRRNOMADS.latest` and processing the results, to just see if it was called without actually testing the logic of `latest`?

**Comment by jomey** [comment]
> This changes the test from actually calling `HRRRNOMADS.latest` and processing the results, to just see if it was called without actually testing the logic of `latest`?

Yes, this makes the `TestCli` a complete Unit-test class, where it test logic that the CLI is responsible for - calling the HRRRNOMADS class with the parameters it was called. 

A functional test would be to call the full stack and should be its own class. Then there should also be no mocking of any kind. Clear separation of functional and unit level tests is from my perspective a better design and testing approach and makes for easier maintenance and helps in identifying where something went wrong when they start to fail.

**Comment by scotthavens** [comment]
Makes sense. This is then really just testing the functionality of the `main` function.

How it was written was more a functional test than a unit test correct? The problem with a true functional test without mocking is the reliance on a 3rd party for testing which I've had trouble with in the past. NOMADS cannot be relied upon to return consistent results.

**Comment by jomey** [comment]
> Makes sense. This is then really just testing the functionality of the `main` function.
> 
> How it was written was more a functional test than a unit test correct? The problem with a true functional test without mocking is the reliance on a 3rd party for testing which I've had trouble with in the past. NOMADS cannot be relied upon to return consistent results.

This is at least on how I distinguish between functional and unit tests. Once you leave the class, you basically doing more of a functional test. Think some also call this integration test, which is probably the better term.

Relying on third part tools or an external website is always a pain and  an ongoing discussions on what the best approach is. I have not found a standard solution myself.

**Comment by scotthavens** [comment]
Guess all that is missing is the integration test from start to finish which would rely on NOMADS. For this package, downloading a 120mb file probably isn't ideal for testing and mocking would be the ideal way to go. The get request for a file is pretty straight forward and it will either be downloaded or it won't.

**Comment by jomey** [comment]
> Guess all that is missing is the integration test from start to finish which would rely on NOMADS. For this package, downloading a 120mb file probably isn't ideal for testing and mocking would be the ideal way to go. The get request for a file is pretty straight forward and it will either be downloaded or it won't.

My suggestion for this would be to have local tests do the actual download and use a mock response on GitHub that returns one of the download files as a response. Then you can still do a full integration test with real data and only exclude the download part. Seems safe enough and changes to the download will be detected by local tests.

**Comment by scotthavens** [comment]
Agree, this would be fairly easy to do with pytest as you could mark them as integration and exclude them on github.

**Comment by jomey** [comment]
> Agree, this would be fairly easy to do with pytest as you could mark them as integration and exclude them on github.

Want me to add something along this line to this PR or should we file an issue for that?

**Comment by scotthavens** [comment]
Seems to make sense that it would be here. Would you go with pytest or use some unit test with discovery?

**Comment by jomey** [comment]
> Seems to make sense that it would be here. Would you go with pytest or use some unit test with discovery?

Right now it seems best to tag onto the existing structure and decide based of a set environment variable. Then do a more thorough introduction of pytest or the likes with a separate PR

**Pull request closed without merging**
